# Generated by Django 2.0.5 on 2018-06-09 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolename', models.TextField(max_length=200)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=200)),
                ('password', models.TextField(max_length=200)),
                ('gender', models.TextField(max_length=10)),
                ('hrole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useradmin.role')),
            ],
            options={
                'db_table': 'userinfo',
            },
        ),
    ]
